owner: ACOMO-FINTECH
repo: status
user-agent: ACOMO

sites:
  - name: ACOMO
    url: $SITE_CORE
  - name: ACOMO Blog
    url: $SITE_BLOG
  - name: ACOMO Ticket
    url: $SITE_TICKET
  - name: ACOMO Mail
    url: $SITE_MAIL

status-website:
  name: ACOMO-status
  favicon: https://acomo.com.pe/img/acomo-logo-icon.png
  theme: night
  metaTags:
    - name: 'robots'
      content: 'noindex'
  cname: status.acomo.com.pe
  logoUrl: https://acomo.com.pe/img/acomo-logo-landing.png
  navbar:
    - title: acomo
      href: http://acomo.com.pe/
    - title: Blog
      href: http://blog.acomo.com.pe/
    - title: Ticket
      href: http://ticket.acomo.com.pe/
workflowSchedule:
  graphs: '0 0 * * *'
  responseTime: '59 * * * *'
  staticSite: '0 1 * * *'
  summary: '0 0 * * *'
  updateTemplate: '0 0 * * *'
  updates: '0 3 * * *'
  uptime: '*/5 * * * *'
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  footer: ACOMO NEGOCIOS FINANCIEROS © 2019 - 2022
